language: python
dist: bionic
python:
  - "3.8"

services:
  - docker

script:
  - docker build -t $DOCKER_USERNAME/ezosync:$TRAVIS_BUILD_NUMBER .
  
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag $DOCKER_USERNAME/ezosync:$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/ezosync:latest

deploy:
  skip_cleanup: true
  provider: script
  script: docker push $DOCKER_USERNAME/ezosync
  on:
    branch: master
