language: python
dist: bionic
python:
  - "3.8"

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

after_success:
  - docker build -t $DOCKER_USERNAME/ezosync:latest .

deploy:
  skip_cleanup: true
  provider: script
  script: docker push $DOCKER_USERNAME/ezosync:latest
  on:
    branch: master
